# Chi-Square Test-

This is used to check if there is significance association between two categorical variables.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats

In [4]:
df = sns.load_dataset('tips')

In [5]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
df_table = pd.crosstab(df['sex'],df['smoker'])
print(df_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [10]:
df_table.values 

array([[60, 97],
       [33, 54]], dtype=int64)

In [11]:
o = df_table.values 
o

array([[60, 97],
       [33, 54]], dtype=int64)

In [15]:
val=stats.chi2_contingency(df_table)
val

(0.008763290531773594, 0.925417020494423, 1, array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [16]:
e = val[3]

In [19]:
rows_in_df_table=2
cols=2
ddof=(rows_in_df_table-1)*(cols-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


$$ \chi^2 = \sum{\frac{\left(o-e\right)^2}{e}}$$
$$ Chi\space square\space Formula $$

In [21]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(o,e)])
chi_square

array([0.00119737, 0.00073745])

In [24]:
chi_square=chi_square[0]+chi_square[1]

In [25]:
chi_square

0.001934818536627623

In [26]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [27]:
p_value=1-chi2.cdf(x=chi_square,df=ddof)
print('p-value:',p_value)

p-value: 0.964915107315732


In [28]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables


In [29]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables
