# IMPORTING LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import math
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# T Test

A t-test is a type of inferential statistic which is used to determine if there is a significant difference between the means of two groups which may be related in certain features


T-test has 2 types : 1. one sampled t-test 2. two-sampled t-test.

# One sample test with python

One sample test tell us weather means of sample and poupation are differten

$$ t = \frac{\bar{x} - \mu}{S_{\bar{x}}} $$ 

where 

$$ S_{\bar{x}} = \frac{S}{\sqrt{n}} $$

$$ \mu = population\space mean$$
$$ \bar{x} = sample\space mean $$
$$ n = sample\space size $$
$$ S = sample\space standard \space deviation $$
$$ S_{\bar{x}} = Estimated\space error \space of \space standard \space mean $$

We have two hypothesis Null Hypothesis and alternate hypothesis.

Null Hypothesis says that there is no difference in the mean of sample and population.

We reject Null Hypothesis if p value is less than 0.05.

In [2]:
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [3]:
len(ages)

32

In [4]:
import numpy as np
ages_mean = np.mean(ages)
ages_mean

30.34375

In [5]:
sample = np.random.choice(ages, size=10)
sample

array([43, 55, 30, 24, 24, 70, 55, 16, 30, 19])

In [6]:
sample_mean =np.mean(sample)

In [7]:
sample_mean

36.6

In [8]:
ttest,p_value=stats.ttest_1samp(sample,30.34375)

In [9]:
p_value

0.30460625720848633

In [10]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis


# SOME MORE EXAMPLES

In [11]:
np.random.seed(6)

In [12]:
population = stats.poisson.rvs(loc = 18,mu =35,size=1500)
sample = stats.poisson.rvs(loc=18,mu=30,size=60)

In [13]:
ttest,p_value=stats.ttest_1samp(a=sample,popmean=population.mean())

In [14]:
p_value

1.139027071016194e-13

In [15]:
population.mean()

53.303333333333335

In [16]:
sample.mean()

46.9

In [17]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")


 we are rejecting null hypothesis


# Two sample test with python

The Independent Samples t Test or 2-sample t-test compares the means of two independent groups in order to determine whether there is statistical evidence that the associated population means are significantly different. The Independent Samples t Test is a parametric test. This test is also known as: Independent t Test



$$ t = \frac{\bar{x_{1}}-\bar{x_{2}}}{\sqrt{S^2\left(\frac{1}{n_{1}}+\frac{1}{n_{2}}\right)}}$$

Where

$$ S^2 = \frac{\sum_{i=1}^{n_{1}}\left(x_{i}-\bar{x_{1}}\right)^2+\sum_{j=1}^{n_{2}}\left(x_{j}-\bar{x_{2}}\right)^2}{n_{1}+n_{2}-1}$$

$$ \bar{x_{1}} = Mean\space of \space first\space group$$
$$ \bar{x_{2}} = Mean\space of \space Second\space group$$
$$ n_{1} = sample\space size\space of \space first\space group $$
$$ n_{2} = sample\space size\space of \space Second\space group $$
$$ S^2 = Estimator \space of \space common \space variance $$

So we have same hypothesis like one sample test null hypothesis and alternate hypothesis

In [18]:
np.random.seed(12)

In [19]:
sample_2 = stats.poisson.rvs(loc=18,mu=33,size=60)

In [20]:
sample

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [21]:
sample_2

array([44, 47, 60, 65, 47, 52, 56, 56, 44, 48, 50, 47, 55, 49, 50, 50, 50,
       41, 53, 47, 39, 50, 52, 43, 53, 51, 59, 53, 51, 46, 41, 53, 63, 53,
       48, 65, 63, 54, 49, 53, 48, 45, 49, 59, 50, 51, 56, 45, 56, 43, 43,
       47, 54, 48, 45, 41, 60, 48, 51, 49])

In [22]:
ttest,p_value=stats.ttest_ind(a=sample,b=sample_2,equal_var=False)

In [23]:
p_value

0.00039942095100859375

In [24]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


# Paired T-test With Python

When you want to check how different samples from the same group are, you can go for a paired T-test

$$ t = \frac{\mu}{S_{\mu}}$$

where

$$ S_{\mu} = Estimated error of standard mean of difference = \frac{S}{\sqrt{n}} $$

$$ \mu = Mean \space of\space difference $$
$$ n = Size\space of\space difference $$

In [25]:
weight1=[25,30,28,35,28,34,26,29,30,26,28,32,31,30,45]
weight2=weight1+stats.norm.rvs(scale=5,loc=-1.25,size=15)

In [26]:
weight1

[25, 30, 28, 35, 28, 34, 26, 29, 30, 26, 28, 32, 31, 30, 45]

In [27]:
weight2

array([30.57926457, 34.91022437, 29.00444617, 30.54295091, 19.86201983,
       37.57873174, 18.3299827 , 21.3771395 , 36.36420881, 32.05941216,
       26.93827982, 29.519014  , 26.42851213, 30.50667769, 41.32984284])

In [28]:
df=pd.DataFrame({"weight_1":np.array(weight1),"weight_2":np.array(weight2),
                 "Difference":np.array(weight2)-np.array(weight1)})


In [29]:
df

weight_1   weight_2  Difference
0         25  30.579265    5.579265
1         30  34.910224    4.910224
2         28  29.004446    1.004446
3         35  30.542951   -4.457049
4         28  19.862020   -8.137980
5         34  37.578732    3.578732
6         26  18.329983   -7.670017
7         29  21.377139   -7.622861
8         30  36.364209    6.364209
9         26  32.059412    6.059412
10        28  26.938280   -1.061720
11        32  29.519014   -2.480986
12        31  26.428512   -4.571488
13        30  30.506678    0.506678
14        45  41.329843   -3.670157

In [30]:
sum(df["Difference"])

-11.669292763480932

In [31]:
ttest,p_value=stats.ttest_rel(a=weight1,b=weight2)

In [32]:
p_value

0.5732936534411279

In [33]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis
